"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { Tag, Check, X, Loader2 } from "lucide-react";

type Props={originalPrice:number;tournamentId?:string;onValidPromo:(promo:any,finalPrice:number,discount:number)=>void;initialCode?:string};
export default function PromoCodeInput({originalPrice,tournamentId,onValidPromo,initialCode=""}:Props){const supabase=createClient();const[code,setCode]=useState(initialCode);const[loading,setLoading]=useState(false);const[result,setResult]=useState<any>(null);const[error,setError]=useState("");
 const check=async()=>{if(!tournamentId)return setError("Tournoi introuvable");setLoading(true);setError("");setResult(null);try{const{data,error}=await supabase.rpc("validate_promo_code",{p_code:code,p_tournament:tournamentId});if(error)throw error;const p=Array.isArray(data)?data[0]:data;if(!p?.valid){const m:any={INVALID:"Code promo invalide",EXPIRED:"Ce code promo a expiré",EXHAUSTED:"Ce code promo n'est plus disponible",TOURNAMENT:"Ce code promo n'est pas valable pour ce tournoi",INACTIVE:"Ce code promo est désactivé",NOT_STARTED:"Cette promotion n'est pas encore active"};setError(m[p?.error_code]||"Code promo invalide");onValidPromo(null,originalPrice,0);return}const d=p.discount_type==="percent"?Math.min(originalPrice,Math.round(originalPrice*p.discount_value/100)):Math.min(originalPrice,Math.max(0,p.discount_value));setResult({...p,discount:d,finalPrice:originalPrice-d});onValidPromo(p,originalPrice-d,d)}catch{setError("Impossible de vérifier le code promo.")}finally{setLoading(false)}};
 return <div className="rounded-2xl border border-dashed border-zinc-700 bg-[#101015] p-4 space-y-3"><div className="flex items-center gap-2 text-xs font-bold uppercase text-zinc-500"><Tag className="h-4 w-4"/>Code promo</div><div className="flex gap-2"><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="PROMO50" className="flex-1 rounded-xl bg-[#15151E] border border-zinc-800 px-4 py-2.5 text-sm uppercase"/><button onClick={check} disabled={loading||!code.trim()} className="rounded-xl bg-white text-black px-4 py-2.5 text-xs font-black">{loading?<Loader2 className="h-4 w-4 animate-spin"/>:"APPLIQUER"}</button></div>{error&&<p className="text-xs text-red-400 flex items-center gap-1"><X className="h-3 w-3"/>{error}</p>}{result&&<div className="rounded-xl bg-emerald-500/10 border border-emerald-500/20 p-3 text-xs"><p className="text-emerald-300 font-bold"><Check className="inline h-3 w-3"/> Code {result.code} appliqué</p><div className="mt-2 space-y-1"><p>Prix initial : {originalPrice.toLocaleString("fr-FR")} FCFA</p><p>Réduction : -{result.discount.toLocaleString("fr-FR")} FCFA{result.discount_type==="percent"?` (-${result.discount_value}%)`:""}</p><p className="font-black text-white">Prix à payer : {result.finalPrice.toLocaleString("fr-FR")} FCFA</p></div></div>}</div>}
