"use client";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Match={id:string;round_number:number;round_name:string;match_number:number;player1?:any;player2?:any;player1_id:string|null;player2_id:string|null;winner_id:string|null;score_player1:number|null;score_player2:number|null;status:string};
export default function PublicBracket({tournamentId}:{tournamentId:string}){
 const supabase=createClient(); const[matches,setMatches]=useState<Match[]>([]);
 useEffect(()=>{const load=async()=>{const{data}=await supabase.from("matches").select("id,round_number,round_name,match_number,player1_id,player2_id,winner_id,score_player1,score_player2,status,player1:player1_id(id,username,display_name,avatar_url),player2:player2_id(id,username,display_name,avatar_url)").eq("tournament_id",tournamentId).eq("type","TOURNOI").order("round_number").order("match_number");setMatches((data||[]) as any)};load();const ch=supabase.channel(`bracket-${tournamentId}`).on("postgres_changes",{event:"*",schema:"public",table:"matches",filter:`tournament_id=eq.${tournamentId}`},load).subscribe();return()=>{supabase.removeChannel(ch)}} , [tournamentId]);
 if(!matches.length)return <div className="rounded-2xl border border-dashed border-zinc-800 p-8 text-center text-sm text-zinc-500">Le bracket sera disponible après génération par l'administration.</div>;
 const rounds=Array.from(new Set(matches.map(m=>m.round_number))).sort((a,b)=>a-b);
 return <div className="overflow-x-auto pb-3"><div className="flex gap-5 min-w-max">{rounds.map(r=><div key={r} className="w-60"><h3 className="mb-3 rounded-xl border border-zinc-800 bg-[#15151E] px-4 py-2 text-center text-xs font-black uppercase tracking-wider">{matches.find(m=>m.round_number===r)?.round_name}</h3><div className="space-y-4">{matches.filter(m=>m.round_number===r).map(m=><div key={m.id} className={`rounded-xl border bg-[#101015] p-3 ${m.winner_id?"border-emerald-500/20":"border-zinc-800"}`}><Player p={m.player1} score={m.score_player1} winner={m.winner_id===m.player1_id}/><div className="my-2 h-px bg-zinc-800"/><Player p={m.player2} score={m.score_player2} winner={m.winner_id===m.player2_id}/><p className="mt-2 text-[9px] text-zinc-600 text-center">{m.status}</p></div>)}</div></div>)}</div></div>
}
function Player({p,score,winner}:{p:any;score:number|null;winner:boolean}){return <div className={`flex items-center gap-2 rounded-lg px-2 py-2 ${winner?"bg-emerald-500/10":"bg-white/[0.02]"}`}><div className="h-7 w-7 rounded-full overflow-hidden bg-gradient-to-br from-violet-600 to-cyan-500 shrink-0">{p?.avatar_url&&<img src={p.avatar_url} className="h-full w-full object-cover" alt=""/>}</div><span className="text-xs font-bold truncate flex-1">{p?.username||"En attente"}</span>{score!==null&&<span className="font-black text-sm">{score}</span>}{winner&&<span>🏆</span>}</div>}
